In [115]:
import streamlit as st

import numpy as np
import pandas as pd 
from numbers import Number
from scipy import stats
from geopy.distance import geodesic

import matplotlib.pyplot as plt
import seaborn as sns

import itertools
import statsmodels.api as sm
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures

In [116]:
st.title("Kings County Housing Dashboard")

st.header("Interactive Housing Predictive Model Widget")

st.subheader("Map of Kings County, WA Housing Data")

DeltaGenerator()

In [117]:
beds = st.selectbox('Select Number of Bedrooms:',[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13])

In [118]:
baths = st.selectbox('Select Number of Bathrooms',[0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0
                                                  ,5.5,6.0, 6.5,7.0,7.5,8.0,8.5,9.5
                                                  ,10.0,10.5])

In [119]:
import pickle

In [120]:
model = pickle.load(open('daniel_pickle.pkl','rb'))
modeled_df = pickle.load(open('df_pickle.pkl','rb'))

In [183]:
ss = pickle.load(open('scaler.pkl','rb'))

In [197]:
test = modeled_df.iloc[0:1,:]

In [202]:
test

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
20693         3        1.5          980      8400     1.0         980   

       sqft_basement  sqft_patio  yr_built  yr_renovated  ...  zip_code_98168  \
20693              0         180      1973             0  ...             0.0   

       zip_code_98177  zip_code_98178  zip_code_98188  zip_code_98198  \
20693             0.0             0.0             0.0             0.0   

       zip_code_98199  zip_code_98224  zip_code_98288  nuisance_NO  \
20693             0.0             0.0             0.0          1.0   

       nuisance_YES  
20693           0.0  

[1 rows x 109 columns]

In [204]:
standardized_test = ss.transform(test)

In [205]:
standardized_test

array([[-4.40295451e-01, -9.34276897e-01, -1.17910085e+00,
        -1.36269391e-01, -9.37177214e-01, -9.59515649e-01,
        -8.22736336e-01, -1.41281768e-01, -2.63302797e-02,
        -2.23643617e-01, -8.42739948e-01,  2.97988074e-01,
         4.48490424e-01, -5.58089877e-01, -6.92506032e-01,
        -3.45736356e-01,  1.32301230e-01, -1.32301230e-01,
         1.64249978e-01, -1.64249978e-01,  1.97964570e+00,
        -4.64876349e-02, -1.49589516e+00, -5.73976296e-02,
        -3.32115823e-01, -9.90099010e-03, -2.62032648e-02,
        -4.16152704e-01, -1.40028008e-02,  4.16557855e-01,
        -7.00088567e-03, -1.45147882e-01, -1.12050025e-01,
        -1.24003869e-01, -1.05357008e-01, -7.85112223e-02,
        -1.34961038e-01, -7.26065771e-02, -1.22363759e-01,
        -1.03679758e-01, -9.53934017e-02, -7.39585455e-02,
        -9.32781365e-02, -1.23799972e-01, -1.60272979e-01,
        -6.31318623e-02, -1.15584693e-01, -1.13609283e-01,
        -1.05594534e-01, -1.15584693e-01,  7.38896002e+0

In [206]:
model.predict(standardized_test)

array([246492.69263808])

In [207]:
new_test = test

In [212]:
test

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
20693         3        1.5          980      8400     1.0         980   

       sqft_basement  sqft_patio  yr_built  yr_renovated  ...  zip_code_98168  \
20693              0         180      1973             0  ...             0.0   

       zip_code_98177  zip_code_98178  zip_code_98188  zip_code_98198  \
20693             0.0             0.0             0.0             0.0   

       zip_code_98199  zip_code_98224  zip_code_98288  nuisance_NO  \
20693             0.0             0.0             0.0          1.0   

       nuisance_YES  
20693           0.0  

[1 rows x 109 columns]

In [232]:
list(test['sqft_living'])

[980]

In [234]:
new_test = test.replace({'sqft_living': list(test['sqft_living'])}, 1500)

In [235]:
new_test

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
20693         3        1.5         1500      8400     1.0         980   

       sqft_basement  sqft_patio  yr_built  yr_renovated  ...  zip_code_98168  \
20693              0         180      1973             0  ...             0.0   

       zip_code_98177  zip_code_98178  zip_code_98188  zip_code_98198  \
20693             0.0             0.0             0.0             0.0   

       zip_code_98199  zip_code_98224  zip_code_98288  nuisance_NO  \
20693             0.0             0.0             0.0          1.0   

       nuisance_YES  
20693           0.0  

[1 rows x 109 columns]

In [236]:
ss.test = ss.transform(new_test)

In [237]:
model.predict(ss.test)

array([313180.69263808])

In [126]:
df = df.replace({'zip_code_98001':0} ,1)

In [127]:
df['zip_code_98001']

0    1.0
Name: zip_code_98001, dtype: float64

In [128]:
sorted(modeled_df.columns)


['bathrooms',
 'bedrooms',
 'condition',
 'distance_to_amazon',
 'floors',
 'grade',
 'greenbelt_NO',
 'greenbelt_YES',
 'heat_source_Electricity',
 'heat_source_Electricity/Solar',
 'heat_source_Gas',
 'heat_source_Gas/Solar',
 'heat_source_Oil',
 'heat_source_Oil/Solar',
 'heat_source_Other',
 'lat',
 'long',
 'nuisance_NO',
 'nuisance_YES',
 'sewer_system_PRIVATE',
 'sewer_system_PRIVATE RESTRICTED',
 'sewer_system_PUBLIC',
 'sewer_system_PUBLIC RESTRICTED',
 'sqft_above',
 'sqft_basement',
 'sqft_living',
 'sqft_lot',
 'sqft_patio',
 'view',
 'waterfront_NO',
 'waterfront_YES',
 'yr_built',
 'yr_renovated',
 'zip_code_98001',
 'zip_code_98002',
 'zip_code_98003',
 'zip_code_98004',
 'zip_code_98005',
 'zip_code_98006',
 'zip_code_98007',
 'zip_code_98008',
 'zip_code_98010',
 'zip_code_98011',
 'zip_code_98014',
 'zip_code_98019',
 'zip_code_98022',
 'zip_code_98023',
 'zip_code_98024',
 'zip_code_98027',
 'zip_code_98028',
 'zip_code_98029',
 'zip_code_98030',
 'zip_code_98031',
 

In [129]:
df = modeled_df.mode().iloc[:1, :]

In [176]:
df

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
0       3.0        2.5         1250    5000.0     1.0      1080.0   

   sqft_basement  sqft_patio  yr_built  yr_renovated  ...  zip_code_98168  \
0            0.0         0.0    2021.0           0.0  ...             0.0   

   zip_code_98177  zip_code_98178  zip_code_98188  zip_code_98198  \
0             0.0             0.0             0.0             0.0   

   zip_code_98199  zip_code_98224  zip_code_98288  nuisance_NO  nuisance_YES  
0             0.0             0.0             0.0          1.0           0.0  

[1 rows x 109 columns]

In [131]:
cols = df.columns

In [132]:
cols = [s.replace('zip_code_', '') for s in cols]

In [134]:
rows = np.linspace(0,0, len(cols))

In [135]:
zeros = pd.DataFrame(rows,cols).T

In [136]:
zeros

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
0       0.0        0.0          0.0       0.0     0.0         0.0   

   sqft_basement  sqft_patio  yr_built  yr_renovated  ...  98168  98177  \
0            0.0         0.0       0.0           0.0  ...    0.0    0.0   

   98178  98188  98198  98199  98224  98288  nuisance_NO  nuisance_YES  
0    0.0    0.0    0.0    0.0    0.0    0.0          0.0           0.0  

[1 rows x 109 columns]

In [137]:
beds = 7
replacer = {'bedrooms': zeros['bedrooms'][0]}

In [138]:
user_pred = zeros.replace(replacer, beds)

In [139]:
user_pred

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
0       7.0        0.0          0.0       0.0     0.0         0.0   

   sqft_basement  sqft_patio  yr_built  yr_renovated  ...  98168  98177  \
0            0.0         0.0       0.0           0.0  ...    0.0    0.0   

   98178  98188  98198  98199  98224  98288  nuisance_NO  nuisance_YES  
0    0.0    0.0    0.0    0.0    0.0    0.0          0.0           0.0  

[1 rows x 109 columns]

In [164]:
user_pred

bedrooms  bathrooms  sqft_living  sqft_lot  floors  sqft_above  \
0       7.0        0.0          0.0       0.0     0.0         0.0   

   sqft_basement  sqft_patio  yr_built  yr_renovated  ...  98168  98177  \
0            0.0         0.0       0.0           0.0  ...    0.0    0.0   

   98178  98188  98198  98199  98224  98288  nuisance_NO  nuisance_YES  
0    0.0    0.0    0.0    0.0    0.0    0.0          0.0           0.0  

[1 rows x 109 columns]

In [ ]:
model.predict

In [178]:
scaled = scaler.transform(df)

In [180]:
scaled

array([[-4.40295451e-01,  1.85494356e-01, -9.01021820e-01,
        -1.89716517e-01, -9.37177214e-01, -8.45388642e-01,
        -8.22736336e-01, -8.73655673e-01,  1.49210965e+00,
        -2.23643617e-01,  1.43699548e-04, -1.02446298e+00,
        -9.85030432e-01, -5.58089877e-01, -6.92506032e-01,
        -3.45736356e-01,  1.32301230e-01, -1.32301230e-01,
         1.64249978e-01, -1.64249978e-01, -5.05140894e-01,
        -4.64876349e-02,  6.68496048e-01, -5.73976296e-02,
        -3.32115823e-01, -9.90099010e-03, -2.62032648e-02,
        -4.16152704e-01, -1.40028008e-02,  4.16557855e-01,
        -7.00088567e-03, -1.45147882e-01, -1.12050025e-01,
        -1.24003869e-01, -1.05357008e-01, -7.85112223e-02,
        -1.34961038e-01, -7.26065771e-02, -1.22363759e-01,
        -1.03679758e-01, -9.53934017e-02, -7.39585455e-02,
        -9.32781365e-02, -1.23799972e-01, -1.60272979e-01,
        -6.31318623e-02, -1.15584693e-01, -1.13609283e-01,
        -1.05594534e-01, -1.15584693e-01, -1.35337043e-0

In [179]:
model.predict(scaled)

array([6.90960566e+17])

In [162]:
#modeled_df.columns

#modeled_df.median().index
modeled_df.median()

bedrooms             3.0
bathrooms            2.5
sqft_living       1960.0
sqft_lot          7578.0
floors               1.5
                   ...  
zip_code_98199       0.0
zip_code_98224       0.0
zip_code_98288       0.0
nuisance_NO          1.0
nuisance_YES         0.0
Length: 109, dtype: float64

In [151]:
df = modeled_df.median().iloc[:1, :]

IndexingError: Too many indexers

In [169]:
go = scaler.transform(df)

In [171]:
go

array([[-4.40295451e-01,  1.85494356e-01, -9.01021820e-01,
        -1.89716517e-01, -9.37177214e-01, -8.45388642e-01,
        -8.22736336e-01, -8.73655673e-01,  1.49210965e+00,
        -2.23643617e-01,  1.43699548e-04, -1.02446298e+00,
        -9.85030432e-01, -5.58089877e-01, -6.92506032e-01,
        -3.45736356e-01,  1.32301230e-01, -1.32301230e-01,
         1.64249978e-01, -1.64249978e-01, -5.05140894e-01,
        -4.64876349e-02,  6.68496048e-01, -5.73976296e-02,
        -3.32115823e-01, -9.90099010e-03, -2.62032648e-02,
        -4.16152704e-01, -1.40028008e-02,  4.16557855e-01,
        -7.00088567e-03, -1.45147882e-01, -1.12050025e-01,
        -1.24003869e-01, -1.05357008e-01, -7.85112223e-02,
        -1.34961038e-01, -7.26065771e-02, -1.22363759e-01,
        -1.03679758e-01, -9.53934017e-02, -7.39585455e-02,
        -9.32781365e-02, -1.23799972e-01, -1.60272979e-01,
        -6.31318623e-02, -1.15584693e-01, -1.13609283e-01,
        -1.05594534e-01, -1.15584693e-01, -1.35337043e-0

In [170]:
model.predict(go)

array([6.90960566e+17])

In [10]:
d = {'Bedrooms': [beds], 'Bathrooms': [baths]}
df = pd.DataFrame(data=d)

In [14]:
list(modeled_df.columns)

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'sqft_above',
 'sqft_basement',
 'sqft_patio',
 'yr_built',
 'yr_renovated',
 'lat',
 'long',
 'distance_to_amazon',
 'grade',
 'condition',
 'view',
 'waterfront_NO',
 'waterfront_YES',
 'greenbelt_NO',
 'greenbelt_YES',
 'heat_source_Electricity',
 'heat_source_Electricity/Solar',
 'heat_source_Gas',
 'heat_source_Gas/Solar',
 'heat_source_Oil',
 'heat_source_Oil/Solar',
 'heat_source_Other',
 'sewer_system_PRIVATE',
 'sewer_system_PRIVATE RESTRICTED',
 'sewer_system_PUBLIC',
 'sewer_system_PUBLIC RESTRICTED',
 'zip_code_98001',
 'zip_code_98002',
 'zip_code_98003',
 'zip_code_98004',
 'zip_code_98005',
 'zip_code_98006',
 'zip_code_98007',
 'zip_code_98008',
 'zip_code_98010',
 'zip_code_98011',
 'zip_code_98014',
 'zip_code_98019',
 'zip_code_98022',
 'zip_code_98023',
 'zip_code_98024',
 'zip_code_98027',
 'zip_code_98028',
 'zip_code_98029',
 'zip_code_98030',
 'zip_code_98031',
 'zip_code_98032',
 'zip_code_9803

In [144]:
''''

response = st.selectbox('Select Standard of Cusom' , ['Standard', 'Custom'])

elif response == 'Custom':   
    
    
    st.image('house_pic.jpg')    
    
    st.subheader('Sir/Mme , YOU need to fill all necessary informations in order    to get a reply to your loan request !')    
    st.sidebar.header("Informations about the client :")    
    gender_dict = {"Male":1,"Female":2}    
    feature_dict = {"No":1,"Yes":2}    
    edu={'Graduate':1,'Not Graduate':2}    
    prop={'Rural':1,'Urban':2,'Semiurban':3}    
    ApplicantIncome=st.sidebar.slider('ApplicantIncome',0,10000,0,)    
    CoapplicantIncome=st.sidebar.slider('CoapplicantIncome',0,10000,0,)    
    LoanAmount=st.sidebar.slider('LoanAmount in K$',9.0,700.0,200.0)    
    Loan_Amount_Term=st.sidebar.selectbox('Loan_Amount_Term',(12.0,36.0,60.0,84.0,120.0,180.0,240.0,300.0,360.0))    
    Credit_History=st.sidebar.radio('Credit_History',(0.0,1.0))    
    Gender=st.sidebar.radio('Gender',tuple(gender_dict.keys()))    
    Married=st.sidebar.radio('Married',tuple(feature_dict.keys()))    
    Self_Employed=st.sidebar.radio('Self Employed',tuple(feature_dict.keys()))    
    Dependents=st.sidebar.radio('Dependents',options=['0','1' , '2' , '3+'])    
    Education=st.sidebar.radio('Education',tuple(edu.keys()))    
    Property_Area=st.sidebar.radio('Property_Area',tuple(prop.keys()))    
    
    
    class_0 , class_3 , class_1, class_2 = 0,0,0,0    if Dependents == '0':        class_0 = 1    elif Dependents == '1':        class_1 = 1    elif Dependents == '2' :        class_2 = 1    else:        class_3= 1    
    Rural,Urban,Semiurban=0,0,0    if Property_Area == 'Urban' :        Urban = 1    elif Property_Area == 'Semiurban' :        Semiurban = 1    else :        Rural=1

SyntaxError: incomplete input (3281254838.py, line 1)

In [147]:
'''

model_cols = ['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'sqft_above',
 'sqft_basement',
 'sqft_patio',
 'yr_built',
 'yr_renovated',
 'lat',
 'long',
 'distance_to_amazon',
 'grade',
 'condition',
 'view',
 'waterfront_NO',
 'waterfront_YES',
 'greenbelt_NO',
 'greenbelt_YES',
 'heat_source_Electricity',
 'heat_source_Electricity/Solar',
 'heat_source_Gas',
 'heat_source_Gas/Solar',
 'heat_source_Oil',
 'heat_source_Oil/Solar',
 'heat_source_Other',
 'sewer_system_PRIVATE',
 'sewer_system_PRIVATE RESTRICTED',
 'sewer_system_PUBLIC',
 'sewer_system_PUBLIC RESTRICTED',
 'zip_code_98001',
 'zip_code_98002',
 'zip_code_98003',
 'zip_code_98004',
 'zip_code_98005',
 'zip_code_98006',
 'zip_code_98007',
 'zip_code_98008',
 'zip_code_98010',
 'zip_code_98011',
 'zip_code_98014',
 'zip_code_98019',
 'zip_code_98022',
 'zip_code_98023',
 'zip_code_98024',
 'zip_code_98027',
 'zip_code_98028',
 'zip_code_98029',
 'zip_code_98030',
 'zip_code_98031',
 'zip_code_98032',
 'zip_code_98033',
 'zip_code_98034',
 'zip_code_98038',
 'zip_code_98039',
 'zip_code_98040',
 'zip_code_98042',
 'zip_code_98045',
 'zip_code_98047',
 'zip_code_98050',
 'zip_code_98051',
 'zip_code_98052',
 'zip_code_98053',
 'zip_code_98055',
 'zip_code_98056',
 'zip_code_98057',
 'zip_code_98058',
 'zip_code_98059',
 'zip_code_98065',
 'zip_code_98070',
 'zip_code_98072',
 'zip_code_98074',
 'zip_code_98075',
 'zip_code_98077',
 'zip_code_98092',
 'zip_code_98102',
 'zip_code_98103',
 'zip_code_98105',
 'zip_code_98106',
 'zip_code_98107',
 'zip_code_98108',
 'zip_code_98109',
 'zip_code_98112',
 'zip_code_98115',
 'zip_code_98116',
 'zip_code_98117',
 'zip_code_98118',
 'zip_code_98119',
 'zip_code_98122',
 'zip_code_98125',
 'zip_code_98126',
 'zip_code_98133',
 'zip_code_98136',
 'zip_code_98144',
 'zip_code_98146',
 'zip_code_98148',
 'zip_code_98155',
 'zip_code_98166',
 'zip_code_98168',
 'zip_code_98177',
 'zip_code_98178',
 'zip_code_98188',
 'zip_code_98198',
 'zip_code_98199',
 'zip_code_98224',
 'zip_code_98288',
 'nuisance_NO',
 'nuisance_YES']
 
 '''

"\n\nmodel_cols = ['bedrooms',\n 'bathrooms',\n 'sqft_living',\n 'sqft_lot',\n 'floors',\n 'sqft_above',\n 'sqft_basement',\n 'sqft_patio',\n 'yr_built',\n 'yr_renovated',\n 'lat',\n 'long',\n 'distance_to_amazon',\n 'grade',\n 'condition',\n 'view',\n 'waterfront_NO',\n 'waterfront_YES',\n 'greenbelt_NO',\n 'greenbelt_YES',\n 'heat_source_Electricity',\n 'heat_source_Electricity/Solar',\n 'heat_source_Gas',\n 'heat_source_Gas/Solar',\n 'heat_source_Oil',\n 'heat_source_Oil/Solar',\n 'heat_source_Other',\n 'sewer_system_PRIVATE',\n 'sewer_system_PRIVATE RESTRICTED',\n 'sewer_system_PUBLIC',\n 'sewer_system_PUBLIC RESTRICTED',\n 'zip_code_98001',\n 'zip_code_98002',\n 'zip_code_98003',\n 'zip_code_98004',\n 'zip_code_98005',\n 'zip_code_98006',\n 'zip_code_98007',\n 'zip_code_98008',\n 'zip_code_98010',\n 'zip_code_98011',\n 'zip_code_98014',\n 'zip_code_98019',\n 'zip_code_98022',\n 'zip_code_98023',\n 'zip_code_98024',\n 'zip_code_98027',\n 'zip_code_98028',\n 'zip_code_98029',\n 'zip